---

- block:

  - name: build /etc/hosts based on Ansible inventory
    template:
      src: "hosts.j2"
      dest: "/etc/hosts"
      mode: "0644"
      owner: "root"
      group: "root"

  tags:
   - hosts
